#!/bin/sh

case "$1" in
	start) cirros-apply local;;
		mode=$(cirros-query dsmode >/dev/null 2>&1) || exit
		[ "$mode" = "net" ] || exit
		cirros-per instance cirros-apply-local cirros-apply local;;
	stop) :;;
	*) msg "unknown argument ${1}";;
esac

# vi: ts=4 noexpandtab
