#!/bin/sh
case "$1" in
	start)
		cirros-query datasource >/dev/null 2>&1 || exit 0
		cirros-per instance userdata cirros-userdata;;
	stop) :;;
	*) msg "unknown argument ${1}";;
esac

# vi: ts=4 noexpandtab
