#!/bin/sh

case "$1" in
	start)
		mode=$(cirros-query dsmode >/dev/null 2>&1) || exit 0
		[ "$mode" = "local" ] || exit 0
		cirros-per instance cirros-apply-local cirros-apply local;;
	stop) :;;
	*) msg "unknown argument ${1}";;
esac

# vi: ts=4 noexpandtab
