#!/bin/sh
case "$1" in
	start)
		cirros-query datasource >/dev/null 2>&1 || exit 0
		cirros-per instance userdata cirros-userdata;;
	stop) :;;
	*) echo "unknown argument ${1}" 1>&2;;
esac

# vi: ts=4 noexpandtab
