#!/bin/sh

case "$1" in
	start)
		mode=$(cirros-query dsmode >/dev/null 2>&1) || exit 0
		[ "$mode" = "net" ] || exit 0
		cirros-per instance cirros-apply-net cirros-apply net;;
	stop) :;;
	*) msg "unknown argument ${1}";;
esac

# vi: ts=4 noexpandtab
