#!/bin/sh

case "$1" in
	start)
		mode=$(cirros-query dsmode 2>/dev/null) || exit 0
		[ "$mode" = "local" ] || exit 0
		cirros-per instance cirros-apply-local cirros-apply local;;
	stop) :;;
	*) echo "unknown argument ${1}" 1>&2;;
esac

# vi: ts=4 noexpandtab
