#!/bin/sh
# vi: ts=4 noexpandtab
#
# The intent of this file is to run before network is up and configure
# things that would need to be configured as a result of file injection
# ie, to bring up a static network

XN=cloud-setup-local
. /usr/share/cloud/functions

start() {
	return 0
}

case "$1" in
	start) start;;
	*) msg "unknown argument ${1}";;
esac
