#!/bin/sh
# vi: ts=4 noexpandtab
# load modules

case "$1" in
	start)
		lxc-is-container && exit 0
		if [ -f /etc/modules ]; then
			[ -d "/lib/modules/$(uname -r)" ] || exit 0
			while read line; do
				line="${line%%#*}"
				[ -n "$line" ] || continue
				modprobe $line
			done < /etc/modules
		fi
		;;
	stop|restart|reload) : ;;
  *)
	echo $"Usage: $0 {start}"
	exit 1
esac

exit $?
