#!/bin/sh
# vi: ts=4 noexpandtab

case "$1" in
	start)
		lxc-is-container && exit 0
		[ -e /dev/root ] || exit 0
		cirros-per once resizefs -- \
			sh -c 'o=/tmp/resize.out;
				resize2fs /dev/root >$o 2>&1 &&
				rm -f $o && exit 0 ||
				echo "resize failed!" 1>&2;
				cat $o 1>&2; exit 1;' resizefs &
		;;
	stop|restart|reload) : ;;
	*)
		echo $"Usage: $0 {start}"
		exit 1
		;;
esac

exit $?
