#!/bin/sh
# vi: ts=4 noexpandtab

case "$1" in
	start)
		lxc-is-container && exit 0
		[ -e /dev/root ] || exit 0
		# here we have to use start-stop-daemon or the resize
		# process gets killed when rc.sysinit ends (LP: #1261710)
		cirros-per once resize-rootfs -- \
			start-stop-daemon --start --background \
				--exec=/sbin/resize-filesystem -- \
				/dev/root /run/resize.rootfs /dev/console
		;;
	stop|restart|reload) : ;;
	*)
		echo $"Usage: $0 {start}"
		exit 1
		;;
esac

exit $?
