#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
	printf "Starting network: "
	/sbin/ifup lo
	/sbin/dhcpcd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/dhcpcd -k
	/sbin/ifdown lo
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

